/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { Ballot } from "./Ballot";
export type { BoardOfTrustees } from "./BoardOfTrustees";
export type { Vote } from "./Vote";

export { Ownable__factory } from "./factories/Ownable__factory";
export { Ballot__factory } from "./factories/Ballot__factory";
export { BoardOfTrustees__factory } from "./factories/BoardOfTrustees__factory";
export { Vote__factory } from "./factories/Vote__factory";
